# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: date-constructor 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "date-constructor".freeze
  s.version = "0.0.1"

  s.required_ruby_version = ">= 3.0"
  s.require_paths = ["lib".freeze]
  s.authors = ["Clifford Heath".freeze]
  s.date = "2024-07-23"
  s.description = "\nDate and DateTime don't have sensible constructors. You can't construct\none using an existing Date/Time, nor by passing a string to be parsed.\nInstead you have to call special-purpose routines. This gem adds some\nsensible options to the existing modes of the constructors\n".freeze
  s.email = "clifford.heath@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "date-constructor.gemspec",
    "lib/date/constructor.rb",
    "test/test_date.rb",
    "test/test_date_arith.rb",
    "test/test_date_attr.rb",
    "test/test_date_base.rb",
    "test/test_date_compat.rb",
    "test/test_date_conv.rb",
    "test/test_date_marshal.rb",
    "test/test_date_new.rb",
    "test/test_date_parse.rb",
    "test/test_date_strftime.rb",
    "test/test_date_strptime.rb",
    "test/test_switch_hitter.rb"
  ]
  s.homepage = "http://github.com/cjheath/date-constructor".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.5.16".freeze
  s.summary = "Add flexible constructors to Ruby's Date and DateTime".freeze

  s.specification_version = 4

  s.add_development_dependency(%q<rake>.freeze, ["~> 13"])
  s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3"])
  s.add_development_dependency(%q<bundler>.freeze, ["~> 2.5"])
  s.add_development_dependency(%q<rdoc>.freeze, ["~> 6"])
end

